id: Test - CrowdStrike Falcon
version: -1
name: Test - CrowdStrike Falcon
fromversion: 5.0.0
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e06c82e8-adf2-4bf2-8ad3-59738eafa12c
    type: start
    task:
      id: e06c82e8-adf2-4bf2-8ad3-59738eafa12c
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 6ad7519f-fa9b-4e1a-88a8-91ad33df874a
    type: regular
    task:
      id: 6ad7519f-fa9b-4e1a-88a8-91ad33df874a
      version: -1
      name: Fetch from instance
      scriptName: FetchFromInstance
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      add_to_context: {}
      brand_name:
        simple: CrowdstrikeFalcon
      expect_data: {}
      instance_name: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 2de16665-52cc-46de-8956-29cfdd0ab74e
    type: regular
    task:
      id: 2de16665-52cc-46de-8956-29cfdd0ab74e
      version: -1
      name: Get detections by filter
      script: '|||cs-falcon-search-detection'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      filter:
        simple: created_timestamp:>'2020-03-05T15:25:00Z'
      ids: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: e2c23fd0-44b0-49cf-8ab2-9f1ee12649c5
    type: condition
    task:
      id: e2c23fd0-44b0-49cf-8ab2-9f1ee12649c5
      version: -1
      name: Assert detections were fetched
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: greaterThanOrEqual
          left:
            value:
              complex:
                root: CrowdStrike
                accessor: Detection
                transformers:
                - operator: count
            iscontext: true
          right:
            value:
              simple: "1"
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 3c9e5ec7-09ad-41e8-802d-8c7918cbe9ec
    type: regular
    task:
      id: 3c9e5ec7-09ad-41e8-802d-8c7918cbe9ec
      version: -1
      name: Get behavior
      script: '|||cs-falcon-get-behavior'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      behavior_id:
        simple: "10197"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 53ca0f1f-dd72-44fc-8ecc-4b01aa01434f
    type: condition
    task:
      id: 53ca0f1f-dd72-44fc-8ecc-4b01aa01434f
      version: -1
      name: Assert 'suspicious_activity' scenario
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: CrowdStrike
                accessor: Behavior.Scenario
            iscontext: true
          right:
            value:
              simple: suspicious_activity
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 90388d17-7c40-4317-8b8c-fea73a7fbdb3
    type: regular
    task:
      id: 90388d17-7c40-4317-8b8c-fea73a7fbdb3
      version: -1
      name: Get multiple devices
      script: '|||cs-falcon-search-device'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      filter: {}
      hostname: {}
      ids:
        simple: c1a4575cd124419db5ed3c1e8ddc2c04,15dbb9d8f06b45fe9f61eb46e829d986
      platform_name: {}
      platfrom_name: {}
      site_name: {}
      status: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: fbb1a2b6-72a3-44e7-8ede-f01a4c6d6dec
    type: condition
    task:
      id: fbb1a2b6-72a3-44e7-8ede-f01a4c6d6dec
      version: -1
      name: Assert devices were fetched
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: greaterThanOrEqual
          left:
            value:
              complex:
                root: CrowdStrike
                accessor: Device
                transformers:
                - operator: count
            iscontext: true
          right:
            value:
              simple: "1"
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: ffa17f6e-8bcb-4bf6-8b1d-54218a65cd93
    type: title
    task:
      id: ffa17f6e-8bcb-4bf6-8b1d-54218a65cd93
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 3170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 83d92769-a280-4b15-8187-7af39c414918
    type: regular
    task:
      id: 83d92769-a280-4b15-8187-7af39c414918
      version: -1
      name: Clear context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 99a2971d-8723-4590-8f49-2689ca854000
    type: regular
    task:
      id: 99a2971d-8723-4590-8f49-2689ca854000
      version: -1
      name: Search for domain IOCs
      description: Returns a list of your uploaded IOCs that match the search criteria
      script: '|||cs-falcon-search-iocs'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      from_expiration_date: {}
      limit: {}
      offset: {}
      policies: {}
      share_levels: {}
      sort: {}
      sources: {}
      to_expiration_date: {}
      types:
        simple: domain
      values: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 1c1d5e42-7a19-4adb-8d51-9bb6c7024264
    type: condition
    task:
      id: 1c1d5e42-7a19-4adb-8d51-9bb6c7024264
      version: -1
      name: Assert domains were fetched
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: inList
          left:
            value:
              simple: CrowdStrike.IOC.Type
            iscontext: true
          right:
            value:
              simple: domain
      - - operator: inList
          left:
            value:
              simple: CrowdStrike.IOC.Value
            iscontext: true
          right:
            value:
              simple: value
      - - operator: inList
          left:
            value:
              simple: CrowdStrike.IOC.Policy
            iscontext: true
          right:
            value:
              simple: none
      - - operator: inList
          left:
            value:
              simple: CrowdStrike.IOC.ShareLevel
            iscontext: true
          right:
            value:
              simple: red
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: 7f20fe7d-ed97-4a97-8440-54ee152c9747
    type: regular
    task:
      id: 7f20fe7d-ed97-4a97-8440-54ee152c9747
      version: -1
      name: Create test IOC
      description: Uploads an indicator for CrowdStrike to monitor.
      script: '|||cs-falcon-upload-ioc'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      description:
        simple: Test ioc
      expiration_days: {}
      ioc_type:
        simple: domain
      policy:
        simple: none
      share_level:
        simple: red
      source:
        simple: Demisto playbook
      value:
        simple: test.domain.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 080ace21-468c-472c-835a-fba2f6aae364
    type: condition
    task:
      id: 080ace21-468c-472c-835a-fba2f6aae364
      version: -1
      name: Assert IOC was created
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "17"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: inList
          left:
            value:
              simple: CrowdStrike.IOC.Value
            iscontext: true
          right:
            value:
              simple: test.domain.com
      - - operator: isEqualString
          left:
            value:
              simple: CrowdStrike.IOC.Description
            iscontext: true
          right:
            value:
              simple: Test ioc
      - - operator: isEqualString
          left:
            value:
              simple: CrowdStrike.IOC.Source
            iscontext: true
          right:
            value:
              simple: Demisto playbook
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 2f8104b8-8a4f-42e5-822c-d8c36bfec4aa
    type: regular
    task:
      id: 2f8104b8-8a4f-42e5-822c-d8c36bfec4aa
      version: -1
      name: Update IOC
      description: Updates an indicator for CrowdStrike to monitor.
      script: '|||cs-falcon-update-ioc'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      description:
        simple: Benign domain IOC
      expiration_days: {}
      ioc_type:
        simple: domain
      policy:
        simple: detect
      share_level: {}
      source: {}
      value:
        simple: test.domain.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2645
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: a34d0a47-5cc8-4257-81ec-aa0aec41150c
    type: condition
    task:
      id: a34d0a47-5cc8-4257-81ec-aa0aec41150c
      version: -1
      name: Assert IOC was updated
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "16"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: inList
          left:
            value:
              simple: CrowdStrike.IOC.Description
            iscontext: true
          right:
            value:
              simple: Benign domain IOC
      - - operator: inList
          left:
            value:
              simple: CrowdStrike.IOC.Policy
            iscontext: true
          right:
            value:
              simple: detect
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: 3564fa1f-e806-4406-88fc-dbe50247ed89
    type: regular
    task:
      id: 3564fa1f-e806-4406-88fc-dbe50247ed89
      version: -1
      name: Delete test IOC
      description: Deletes a monitored indicator.
      script: '|||cs-falcon-delete-ioc'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      type:
        simple: domain
      value:
        simple: test.domain.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2995
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: 689656bc-44c5-437d-844f-78903a6f40c2
    type: regular
    task:
      id: 689656bc-44c5-437d-844f-78903a6f40c2
      version: -1
      name: Clear context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "18":
    id: "18"
    taskid: 0fb8f1c9-c659-4e9d-86e3-88a11f6c921b
    type: regular
    task:
      id: 0fb8f1c9-c659-4e9d-86e3-88a11f6c921b
      version: -1
      name: Get just created test IOC
      description: Get the full definition of one or more indicators that you are
        watching
      script: '|||cs-falcon-get-ioc'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      type:
        simple: domain
      value:
        simple: test.domain.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "19":
    id: "19"
    taskid: 6eb0d469-cc50-4b43-8b9d-7d2c0dcd863d
    type: condition
    task:
      id: 6eb0d469-cc50-4b43-8b9d-7d2c0dcd863d
      version: -1
      name: Assert IOC was fetched
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "14"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: inList
          left:
            value:
              simple: CrowdStrike.IOC.Value
            iscontext: true
          right:
            value:
              simple: test.domain.com
      - - operator: isEqualString
          left:
            value:
              simple: CrowdStrike.IOC.Description
            iscontext: true
          right:
            value:
              simple: Test ioc
      - - operator: isEqualString
          left:
            value:
              simple: CrowdStrike.IOC.Source
            iscontext: true
          right:
            value:
              simple: Demisto playbook
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 3185,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
